baseurl = "http://www.example.com"
canonifyurls = true
defaultcontentlanguage = "en"
disqusShortname = "yourdiscussshortname"
languagecode = "en"
paginate = 20
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "bw"
theme = "hugo-coder"
title = "johndoe"
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1
[params]
author = "John Doe"
avatarurl = "images/avatar.jpg"
custom_css = ["css/custom.css"]
description = "John Doe's personal website"
favicon_16 = "/img/favicon-16x16.png"
favicon_32 = "/img/favicon-32x32.png"
footercontent = "Enter a text here."
hidecopyright = false
hidecredits = false
info = "Full Stack DevOps and Magician"
keywords = "blog,developer,personal"
math = true
rtl = false
[[params.social]]
icon = "fab fa-github fa-2x"
name = "Github"
url = "https://github.com/johndoe/"
weight = 1
[[params.social]]
icon = "fab fa-gitlab fa-2x"
name = "Gitlab"
url = "https://gitlab.com/johndoe/"
weight = 2
[[params.social]]
icon = "fab fa-twitter fa-2x"
name = "Twitter"
url = "https://twitter.com/johndoe/"
weight = 3
